### ISSUE TITLE
history.py example is not working

### ISSUE THREAD

**Issue by JfourierX** [ranaroussi/ezibpy#1]
First, thanks for the excellent work with qtpy and ezibpy.

I see following error with the supplied history.py example. It works fine for futures though
<error id=1, errorCode=321, errorMsg=Error validating request:-'yd' : cause - HMDS Expired Contract Violation:contract can not expire.>

**Comment by ranaroussi** [comment]
Fixed with commit https://github.com/ranaroussi/ezibpy/commit/736d0329d39db1aa7991264759ec7888b3cab213 .

Please upgrade to latest version of ezIBpy (1.12.20):
`$ pip install ezibpy --upgrade`
