### ISSUE TITLE
move target order？

### ISSUE THREAD

**Issue by 4ever911** [ranaroussi/ezibpy#11]
For bracket orders,there is a function to move the stop order. Can we move the other target order?

**Comment by ranaroussi** [comment]
Sure! 

You can modify an existing order by submitting a new order and providing the `orderId` of the order you with to modify, like so:

```python


order = ibConn.createBracketOrder(contract, quantity=1, entry=0, target=2200., stop=1900.)


return {
            "group": group,
            "entryOrderId": entryOrderId,
            "targetOrderId": targetOrderId,
            "stopOrderId": stopOrderId
            }
 if order['order_type'] == "STOP":
                        new_order = self.ibConn.createStopOrder(
                            quantity = order_quantity,
                            parentId = order['parentId'],
                            stop     = limit_price,
                            trail    = None,
                            transmit = True
                            )


ibConn.placeOrder(contract, new_order, orderId=existing_order_id)
```

order = self.orders.history[symbol][orderId]
                    if order['order_type'] == "STOP":
                        new_order = self.ibConn.createStopOrder(
                            quantity = order_quantity,
                            parentId = order['parentId'],
                            stop     = limit_price,
                            trail    = None,
                            transmit = True
                            )

ibConn.placeOrder(contract, new_order, orderId=orderId)

**Comment by ranaroussi** [comment]
Sure! 

You can modify an existing order by submitting a new order and providing the `orderId` of the order you with to modify, like so:

```python
ibConn.placeOrder(contract, new_order, orderId=existing_order_id)
```

As for moving stops, there's an easier way: 😃 

```python
ibConn.modifyStopOrder(existing_orderId, existing_order_parentId, newStop, quantity):
```

**Comment by ranaroussi** [comment]
Closing this for now.
