### ISSUE TITLE
order type and destination

### ISSUE THREAD

**Issue by mcg88** [ranaroussi/ezibpy#12]
Hello,

I'm trying to figure out if it is possible to set the order type and the order destination explicitly when sending an order. 

Line 1375 in ezibpy.py defines the params for the order but I'm not sure those two items are available to be modified.

Thanks

**Comment by ranaroussi** [comment]
Of course you can :)

The default order type is set to **MKT** if `price` is either 0 or not set, and **LMT** if `price` is set.

That, being said, if you want to use a different order type, simply add the `orderType` parameter to the `createOrder(...)` method with any of the [supported order types](https://www.interactivebrokers.com/en/software/api/apiguide/tables/supported_order_types.htm) and you're good to go.

For Stop/Target orders, I suggest you check out `createStopOrder()`, `createTrailingStopOrder()`, `createTargetOrder()`and `createBracketOrder()`.

**Comment by ranaroussi** [comment]
Closing this for now. Please re-open if needed
