### ISSUE TITLE
[#162] Historical Market Data Service error message:No historical market data for EUR/CASH@FXSUBPIP Last 1d

### ISSUE THREAD

**Issue by dsoong1** [ranaroussi/ezibpy#24]
error retrieving FX cash historical data (i.e. EUR.USD).
Interactive Brokers does not disseminate TRADES data for cash FX. You need to use a different value for whatToShow than the default.

solution:
````python
def requestHistoricalData(...):
    self.ibConn.reqHistoricalData(
                tickerId       = tickerId,
                contract       = contract,
                endDateTime    = end_datetime,
                durationStr    = lookback,
                barSizeSetting = resolution,
                whatToShow     = data, <<<<<
                useRTH         = int(rth),
                formatDate     = int(format_date)
            )
````
if contract.m_secType in ['CASH', 'CFD'], then override whatToShow=="MIDPOINT" or "BID" or "ASK", instead of "TRADES"

**Comment by ranaroussi** [comment]
The parameter ``data`` is changeable... Just use:

```python
ibConn.requestHistoricalData(..., data='MIDPOINT')
```

That being said, I've updated the method to default to MIDPOINT when requesting data for CASH/CFD.
