### ISSUE TITLE
Delete Position

### ISSUE THREAD

**Issue by iranmilad** [ranaroussi/ezibpy#28]
hi 
thank for your library 
this is too easy use 
i have a ask i need a function for delete a position (with a example for this work ) so 
i need a function for get position with id until use for delete this position any time i want

**Comment by ranaroussi** [comment]
You can't delete a position. If you want to exit a position, you need to submit an order for the same ticker in the opposite direction.

If you're long 100 shares of AAPL, you need to submit an order to sell 100 shares of AAPL (``qty=-100``).

Hope that helps :)
