### ISSUE TITLE
historicaldata

### ISSUE THREAD

**Issue by thomaschen2019** [ranaroussi/ezibpy#7]
I am very new to this and I tried with
```python
ibConn = ezibpy.ezIBpy()
ibConn.connect(clientId=4, host="localhost", port=7496)
contract1 = ibConn.createStockContract("BAC")
ibConn.requestHistoricalData(resolution = "5 mins", lookback ="2 D", csv_path = '~/Desktop/5mindata/')
```
then i got
```
2016-12-13 00:46:44,667 [ERROR] ezibpy: [#321] Error validating request:-'bh' : cause - Please enter exchange
```

sometimes after this msg pop up i still can get the data in csv file but sometime it doesn't work.

**Comment by ranaroussi** [comment]
I ran your code without problems. 

Can you try running the code again, but this time be more specific when creating the contract and specify the exchange (via `exchange=...`)?

**Comment by ranaroussi** [comment]
Closing this for now...
