### ISSUE TITLE
No exchange information in contracts

### ISSUE THREAD

**Issue by nowfornext** [ranaroussi/ezibpy#8]
using ezIBpy (1.12.44).
codes below:

ibConn = ezibpy.ezIBpy()
ibConn.connect(clientId=100, host="localhost", port=4001)
print(ibConn.contracts[1].m_exchange)

there are positions in my account. it seems ezibpy created contracts based upon my positions. However, the created contracts did not have the exchange information. This caused issues later to place the orders.

**Comment by ranaroussi** [comment]
This was fixed in 1.12.45. Upgrade to the latest version to get this fixed.

```bash
$ pip install ezibpy --upgrade --no-cache-dir
```

Cheers!

**Comment by nowfornext** [comment]
It works! I should have checked first.

Thanks!
